---

- name: Install the repository RPM
  dnf:
      name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
      state: present
      disable_gpg_check: yes

- name: Disable the built-in PostgreSQL module
  command: dnf -qy module disable postgresql

- name: Install postgresql packages
  dnf:
      name: "{{ item }}"
      state: present
      disable_gpg_check: yes
  with_items:
      - postgresql12
      - postgresql12-server

- name: Make sure pexpect is installed
  pip:
      name: pexpect
      state: present